# Generated by Django 2.1 on 2021-07-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auto_20210726_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='status',
            field=models.CharField(choices=[('inprogress', 'In-Progress'), ('futureselling', 'Future Selling'), ('sold', 'Sold')], default='futureselling', max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='art',
            name='EndTime',
            field=models.DateTimeField(blank=True, verbose_name='Auction EndTime'),
        ),
        migrations.AlterField(
            model_name='art',
            name='auctionimage',
            field=models.ImageField(upload_to='auctionimage/', verbose_name='Auction Image'),
        ),
        migrations.AlterField(
            model_name='art',
            name='buyingPrice',
            field=models.IntegerField(default=0, verbose_name='Buying Price'),
        ),
        migrations.AlterField(
            model_name='art',
            name='description',
            field=models.TextField(verbose_name='Art Inspiration'),
        ),
        migrations.AlterField(
            model_name='art',
            name='reservedPrice',
            field=models.IntegerField(default=0, verbose_name='Reserved Price'),
        ),
        migrations.AlterField(
            model_name='art',
            name='startTime',
            field=models.DateTimeField(blank=True, verbose_name='Auction StartTime'),
        ),
        migrations.AlterField(
            model_name='art',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Art Title'),
        ),
        migrations.AlterField(
            model_name='art',
            name='typeCategory',
            field=models.CharField(choices=[('LandScape', 'LandScape'), ('Portrait', 'Portrait')], default='Portrait', max_length=50, null=True, verbose_name='Art Orienation'),
        ),
    ]
