# Generated by Django 2.1 on 2021-07-27 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auto_20210726_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidprice', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='art',
            name='buyingPrice',
            field=models.IntegerField(default=0, verbose_name='Buying Price (Ksh)'),
        ),
        migrations.AlterField(
            model_name='art',
            name='reservedPrice',
            field=models.IntegerField(default=0, verbose_name='Reserved Price (Ksh)'),
        ),
        migrations.AddField(
            model_name='bid',
            name='art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.Art'),
        ),
        migrations.AddField(
            model_name='bid',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.Profile'),
        ),
    ]
