# Generated by Django 2.1 on 2021-07-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_interested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='art',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='buyer',
        ),
        migrations.AddField(
            model_name='interested',
            name='bidprice',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
