# Generated by Django 2.1 on 2021-07-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_auto_20210727_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='status',
            field=models.CharField(choices=[('inprogress', 'In-Progress'), ('futureselling', 'Future Selling'), ('sold', 'Sold'), ('nobidders', 'nobidders')], default='futureselling', max_length=50, null=True, verbose_name='Status'),
        ),
    ]
